### ISSUE TITLE
Disable in CI

### ISSUE THREAD

**Issue by Diokuz** [unjs/webpackbar#109]
Is that possible to disable webpackbar in CI with process.env?

<img width="759" alt="Снимок экрана 2022-06-16 в 09 50 49" src="https://user-images.githubusercontent.com/2929442/174009572-af4bae28-3f8e-4f18-916c-52643e6a581a.png">

**Comment by brunojppb** [comment]
Yes. it's possible.
During CI, make sure that you don't use the plugin based on an environment variable. Something like this:

```js
const webpack = require('webpack');
const WebpackBar = require('webpackbar');

module.exports = {
  context: path.resolve(__dirname),
  devtool: 'source-map',
  entry: './entry.js',
  output: {
    filename: './output.js',
    path: path.resolve(__dirname)
  },
  plugins: [
    ...(process.env.CI === '1' ? [] : [ new WebpackBar() ])
  ]
};
```

**Comment by joacub** [comment]
Is there another solution to do not have that many lines without disabled it ?

**Comment by brunojppb** [comment]
> Is there another solution to do not have that many lines without disabled it ?

The only line that you need is this one:
```js
    ...(process.env.CI === '1' ? [] : [ new WebpackBar() ])
```

Everything else is part of your Webpack config as usual. This is how you can toggle the feature in CI.

**Comment by joacub** [comment]
> 

Yeah that disable the utility, and we don’t want to disable we want to have that working as usual but not generating that many lines. Do you know how to tell the ci to reuse the lines effectively?

**Comment by brunojppb** [comment]
Unfortunately, I don’t see the point of having that plug-in enabled in CI. This is a plug-in for feedback mostly during development.

your CI output is just a stream of logs that don’t behave as exactly as your local terminal during development.

**Comment by joacub** [comment]
> Unfortunately, I don’t see the point of having that plug-in enabled in CI. This is a plug-in for feedback mostly during development.
> 
> your CI output is just a stream of logs that don’t behave as exactly as your local terminal during development.

We follow the ci integrations in productions sometimes and we want to see the progress of the build that’s why. I try many things but no one worked

**Comment by pi0** [comment]
Webpackbar should use the basic reporter when [minimal env](https://github.com/unjs/std-env/blob/main/src/flags.ts#L32) is detected.

If you have issue with specific CI, please feel free to open a new issue with reproduction steps.
