### ISSUE TITLE
Output after termination

### ISSUE THREAD

**Issue by magic-m-johnson** [unjs/webpackbar#121]
### Environment

Node LTS
Webpack 5
React 18

### Reproduction

Just setup a really simple React app with Webpack 5

### Describe the bug

I get output "closing watch compilation" after i terminal the webpack process, for example via webpack dev server.

### Additional context

We also use verbose mode and TimeAnalyticsPlugin

**Comment by pi0** [comment]
closing as it is an old issue. please ping to reopen if you could reproduce still.
