### ISSUE TITLE
Webpackbar 6 breaks colour keywords

### ISSUE THREAD

**Issue by mikehdt** [unjs/webpackbar#134]
### Environment

Node 20.10

### Reproduction

It seems that keywords are broken in 6.0.0, per this line:
https://github.com/unjs/webpackbar/compare/v5.0.2...v6.0.0#diff-e73cdeee46ab1f69d799626d022665669b44665cf80c4e35412a780ecbf39f25R16

### Describe the bug

Named colours are broken as they seem to have been commented out?

### Additional context

Edit, upon further reading: I suspect this was because Chalk 5 removed these. May have been worth noting in the changelog? 😅 

At the least, the readme should be changed to no longer refer to `green` / named colours:
https://github.com/unjs/webpackbar?tab=readme-ov-file#color

**Comment by pi0** [comment]
It should be fixed in next (major version) via https://github.com/unjs/webpackbar/pull/145
