### ISSUE TITLE
Have same formatting output as Listr (or make it an option)

### ISSUE THREAD

**Issue by Aghassi** [unjs/webpackbar#28]
### What problem does this feature solve?

This is a really minor nit, but this formatting drives me crazy 
![Screen Shot 2018-11-07 at 4.49.52 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/126595796/3c5f0a10-e2f0-11e8-9934-e1f8c6b4dbaa.png)

As far as I'm aware, I'm not sure if your new custom reporters will solve this problem. All I want is for the checkmarks to line up and not to have that new line above. I'm combining your module with https://github.com/SamVerschueren/listr in tandem, hence the concern. This has literally zero effect on the actual use of this repo. I just want to align the outputs 😭.

### What does the proposed changes look like?

Remove the new line​ above the completed step
Align the checkmark with a single space indentation

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/webpackbar/issues/c21">#c21</a>)</em></sub></div>

**Comment by pi0** [comment]
https://github.com/unjs/webpackbar/pull/34#issuecomment-1857785882
