### ISSUE TITLE
stats.json messed up with outputs from webpackbar

### ISSUE THREAD

**Issue by shahzaibkhalid** [unjs/webpackbar#42]
First of all, thanks so much for this wonderful progress bar.

I was using webpackbar and tried to write a `stats.json` file to be used by `webpack-bundle-analyzer`.

Here's my npm script:

`webpack --env=production --profile --json > stats.json`

However, stats.json contains some output from webpackbar. Here's how it looks like:

```json
ℹ Compiling Webpack                                        webpackbar 18:06:57
✔ Webpack: Compiled successfully in 3.22s                  webpackbar 18:07:00
{
  "errors": [],
  "warnings": [],
  "version": "4.29.3",
  "hash": "ed64caf72379ba267639",
  "time": 3228,
  "builtAt": 1549976820840,
  "publicPath": "/",
  "outputPath": "/Users/shahzaib/my-stuff/serious-projects/testing-shaizei/copy-jetsetter/build",
  "assetsByChunkName": {
    "main": [
    // remaining file is not included for brevity
}
```

Due to these two lines (in the start), `stats.json` is becoming invalid.

Any workaround for this?

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/webpackbar/issues/c33">#c33</a>)</em></sub></div>

**Comment by Airkro** [comment]
webpack-bundle-analyzer can write stats.json by himself

**Comment by shahzaibkhalid** [comment]
@airkro What do you mean? Can you please explain it a bit?

What I got to know was that our webpack config shouldn't have any `console.log` because those logs can end-up in `stats.json`.

**Comment by Airkro** [comment]
I don't know if this is what you want, but have you tried this?

```js
new BundleAnalyzerPlugin({
  analyzerMode: 'static',
  generateStatsFile: true,  //  <----------------
  reportFilename: 'xxx/stats.html',
  statsFilename: 'xxx/stats.json'
})
```

**Comment by Airkro** [comment]
In many cases, we use the terminal as a user interface, and countless plugins use the `console` API. So I think any output from the terminal is untrustworthy, I don't recommend using `whatever --foo --bar > files.json`

**Comment by shahzaibkhalid** [comment]
I got you. I was preferring the use of CLI for `webpack-bundle-analyzer` but now I see why the other way is recommended.

**Comment by thasmo** [comment]
When using the `--json` flag via `webpack-cli` the `webpackbar` plugin should not output ...
```
webpackbar 13:14:00 ℹ Compiling Webpack
webpackbar 13:14:04 ✔ Webpack: Compiled successfully in 3.40s
```
... because it makes the JSON output invalid.

Will this issue be worked on in the future or are there any reasons it has not been closed yet? Thanks!

**Comment by krishan** [comment]
WFIW I just got bitten by this problem also. 

The official webpack documentation _does_ recommends to use `stdout`, therefore I don't think it wise for a plugin to break this standard functionality.

This is from the official webpack docs:
```
webpack --profile --json > compilation-stats.json
```
See: https://webpack.js.org/api/stats/

**Comment by cweekly** [comment]
Yeah this is not specific to webpackbar. I ran into the same thing with webpack-bundle-analyzer. Despite the official docs cited by @krishan above, any console output appears in the generated file (eg `stats.json`), effectively breaking the mechanism. Ideally, this would be fixed in webpack-cli per  @thasmo's comment https://github.com/nuxt/webpackbar/issues/42#issuecomment-491254131

**Comment by pi0** [comment]
`--json` seems to be working well now (after output)

<img width="1035" alt="image" src="https://github.com/user-attachments/assets/26199775-f2bd-4b9f-84e6-726b48caedc3">
