### ISSUE TITLE
Looking forward to a support for index.d.ts, because it is inconvenient to use without TypeScript

### ISSUE THREAD

**Issue by yuchonghua** [unjs/webpackbar#44]
Looking forward to a support for index.d.ts, because it is inconvenient to use without TypeScript
![img](https://cmty.s3.eu-west-1.amazonaws.com/126595796/546dd4a0-5123-11e9-b24f-9b8890408f45.png)

https://cmty.app/nuxt/webpackbar/issues/c35

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/webpackbar/issues/c36">#c36</a>)</em></sub></div>

**Comment by pi0** [comment]
Latest versions of webpackbar ship type declarations.

If you still had issues and could reproduce please ping to reopen.
