### ISSUE TITLE
Support webpack 5

### ISSUE THREAD

**Issue by otakustay** [unjs/webpackbar#73]
### What problem does this feature solve?

I used webpackbar with webpack 5 for a while and found no compatibility issue, since npm 7 requires peer dependencies to match strictly, it is better to publish a new version upgrading peerDependencies to enable webpack 5

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/webpackbar/issues/c47">#c47</a>)</em></sub></div>

**Comment by pi0** [comment]
webpack5 is tested in main branch. 

If there is any (reproducable) issues with wp5 support please report in a new issue 🙏🏼
