### ISSUE TITLE
progressbar display problem

### ISSUE THREAD

**Issue by goldenfireking** [unjs/webpackbar#84]
<img width="728" alt="截屏2021-04-30 上午11 17 09" src="https://user-images.githubusercontent.com/26026611/116645522-a56e4800-a9a8-11eb-82c8-054ef77f6a58.png">

webpack 4.46.0

**Comment by njradford** [comment]
+ 1

**Comment by pi0** [comment]
please consider sharing a reproduction if still having issues with latest versions.
