### ISSUE TITLE
It will not be displayed during the build process, only the result will be displayed when the build is complete

### ISSUE THREAD

**Issue by arleyGuoLei** [unjs/webpackbar#96]
FYI

![image](https://user-images.githubusercontent.com/40717741/150094077-98aad18b-504e-4de3-9f79-0c78653495fc.png)

- webpack 5.65.0

May be conflicting with what configuration ?

**Comment by arleyGuoLei** [comment]
link package is broken in case (development), direct installation package will display normally

**Comment by daniele-orlando** [comment]
Same issue, with linked packages.

**Comment by mihanizm56** [comment]
[arleyGuoLei](https://github.com/arleyGuoLei) what do you mean by "direct installation package" ?

**Comment by pi0** [comment]
please consider opening a new issue with runnable reproduction.
