### ISSUE TITLE
Cannot read property 'tap' of undefined.

### ISSUE THREAD

**Issue by Hongbusi** [unjs/webpackbar#99]
# Cannot read property 'tap' of undefined.

## Environment

``` json
"webpack": "^5.68.0",
"webpackbar": "^5.0.2"
```

## Problem

``` js
const webpack = require('webpack');
const WebpackBar = require('webpackbar');

const compiler = webpack([{}, {}]);

new WebpackBar().apply(compiler);
```

`compiler.hooks[hookName].tap("WebpackBar:" + hookName, fn);`

## Reason

Multi compiler not supported.

**Comment by pi0** [comment]
in repo playground we test webpack5 with multi compiler. feel free to reopen if you could reproduce it against latest version.
